include(dependencies/SparseHash)

set(UtilitiesLib_SOURCE_FILES
	src/components/ArrayOld.c
	src/components/AssociationList.c
	src/components/AutoStructSupport.c
	src/components/BinarySearchTree.c
	src/components/BitArray.c
	src/components/bitfield.c
	src/components/BitStream.c
	src/components/BloomFilter.c
	src/components/datalist.c
	src/components/datapool.c
	src/components/earray.c
	src/components/EString.c
	src/components/FilespecMap.c
	src/components/Frustum.c
	src/components/genericlist.c
	src/components/GenericMesh.c
	src/components/GenericPoly.c
	src/components/gridpoly.c
	src/components/HashFunctions.c
	src/components/HashTableStack.c
	src/components/mailbox.c
	src/components/MemAlloc.c
	src/components/MemoryBank.c
	src/components/MemoryPool.c
	src/components/MemRef.c
	src/components/metadictionary.c
	src/components/MRUList.c
	src/components/MultiVal.c
	src/components/NamedBitArray.c
	src/components/Octree.c
	src/components/PerformanceCounter.c
	src/components/Queue.c
	src/components/ReferenceList.c
	src/components/ReferenceSystem.c
	src/components/RingBuffer.c
	src/components/SharedHeap.c
	src/components/sharedmalloc.c
	src/components/SharedMemory.c
	src/components/SharedQueue.c
	src/components/SimpleSet.c
	src/components/StashTable.c
	src/components/StringCache.c
	src/components/StringTable.c
	src/components/TriCube/fpcube.c
	src/components/TriCube/pcube.c
	src/components/WorkerThread.c
	src/language/AppLocale.c
	src/language/MessageStore.c
	src/language/MessageStoreUtil.c
	src/language/MultiMessageStore.c
	src/network/bignum.c
	src/network/bindiff.c
	src/network/blowfish.c
	src/network/crc32c.cpp
	src/network/crypt.cpp
	src/network/fingerprint.c
	src/network/ftpclient.c
	src/network/netcomp.c
	src/network/netio_core.c
	src/network/netio_receive.c
	src/network/netio_send.c
	src/network/netio_stats.c
	src/network/NetworkSpecifier.c
	src/network/net_link.c
	src/network/net_linklist.c
	src/network/net_masterlist.c
	src/network/net_masterlistref.c
	src/network/net_packet.c
	src/network/net_packetutil.c
	src/network/net_profile.c
	src/network/net_socket.c
	src/network/net_version.c
	src/network/rsa.c
	src/network/sock.c
	src/utilitiesLib.c
	src/UtilsCXX/ringchain.cpp
	src/UtilsCXX/threadedpoolallocator.cpp
	src/UtilsNew/array.c
	src/UtilsNew/Bits.c
	src/UtilsNew/hashfunctions/lookup3.c
	src/UtilsNew/lock.c
	src/UtilsNew/meta.c
	src/UtilsNew/ncHash.cpp
	src/UtilsNew/ncstd.c
	src/UtilsNew/ncutils.cpp
	src/UtilsNew/ntapiext.c
	src/UtilsNew/profiler.c
	src/UtilsNew/Str.c
	src/UtilsNew/Stream.c
	src/UtilsNew/timer.c
	src/utils/Breakpoint.c
	src/utils/buildVersion.c
	src/utils/cmdoldparse.c
	src/utils/Color.c
	src/utils/CommandFileParser.c
	src/utils/ConsoleDebug.c
	src/utils/contextQsort.c
	src/utils/ConvertUtf.c
	src/utils/cpu_count.c
	src/utils/dds.c
	src/utils/DebugState.c
	src/utils/DirMonitor.c
	src/utils/dobbs_hash.c
	src/utils/endian.c
	src/utils/error.c
	src/utils/eval.c
	src/utils/file.c
	src/utils/fileutil.c
	src/utils/fileWatch.c
	src/utils/FolderCache.c
	src/utils/FolderCacheNode.c
	src/utils/genericDialog.c
	src/utils/hoglib.c
	src/utils/hogutil.c
	src/utils/LineDist.c
	src/utils/ListView.c
	src/utils/log.c
	src/utils/mathutil.c
	src/utils/memcheck.c
	src/utils/memlog.c
	src/utils/MemoryHeap.cpp
	src/utils/MemoryMonitor.c
	src/utils/memtrack.c
	src/utils/mutex.c
	src/utils/osdependent.c
	src/utils/PigDir.c
	src/utils/PigFileWrapper.c
	src/utils/piglib.c
	src/utils/process_util.c
	src/utils/qsortG.c
	src/utils/Quat.c
	src/utils/quick_sprintf.c
	src/utils/rand.c
	src/utils/RegistryReader.c
	src/utils/rgb_hsv.c
	src/utils/scriptvars.c
	src/utils/serialize.c
	src/utils/SimpleParser.c
	src/utils/ssemath.c
	src/utils/Stackdump.c
	src/utils/strings_opt.c
	src/utils/StringUtil.c
	src/utils/structDefines.c
	src/utils/structHist.c
	src/utils/structInternals.c
	src/utils/structNet.c
	src/utils/structTokenizer.c
	src/utils/SuperAssert.c
	src/utils/sysutil.c
	src/utils/textparser.c
	src/utils/textparserReg.c
	src/utils/textparserUtils.c
	src/utils/tga.c
	src/utils/threadedFileCopy.c
	src/utils/tiff.c
	src/utils/timing.c
	src/utils/tokenstore.c
	src/utils/UnitSpec.c
	src/utils/utils.c
	src/utils/utils_opt.c
	src/utils/winfiletime.c
	src/utils/WinTabUtil.c
	src/utils/winutil.c
	src/version/AppRegCache.c
	src/version/AppVersion.c
)

set(UtilitiesLib_HEADER_FILES
	include/utilitieslib/AppVersionDefines.h
	include/utilitieslib/assert/assert.h
	include/utilitieslib/components/ArrayOld.h
	include/utilitieslib/components/AssociationList.h
	include/utilitieslib/components/BinarySearchTree.h
	include/utilitieslib/components/BitArray.h
	include/utilitieslib/components/bitfield.h
	include/utilitieslib/components/BitStream.h
	include/utilitieslib/components/BloomFilter.h
	include/utilitieslib/components/datalist.h
	include/utilitieslib/components/datapool.h
	include/utilitieslib/components/earray.h
	include/utilitieslib/components/EString.h
	include/utilitieslib/components/FilespecMap.h
	include/utilitieslib/components/Frustum.h
	include/utilitieslib/components/genericlist.h
	include/utilitieslib/components/GenericMesh.h
	include/utilitieslib/components/GenericPoly.h
	include/utilitieslib/components/gridpoly.h
	include/utilitieslib/components/HashFunctions.h
	include/utilitieslib/components/HashTableStack.h
	include/utilitieslib/components/mailbox.h
	include/utilitieslib/components/MemoryBank.h
	include/utilitieslib/components/MemoryPool.h
	include/utilitieslib/components/MemRef.h
	include/utilitieslib/components/MetaDictionary.h
	include/utilitieslib/components/MRUList.h
	include/utilitieslib/components/MultiVal.h
	include/utilitieslib/components/NamedBitArray.h
	include/utilitieslib/components/Octree.h
	include/utilitieslib/components/PerformanceCounter.h
	include/utilitieslib/components/Queue.h
	include/utilitieslib/components/ReferenceList.h
	include/utilitieslib/components/referencesystem.h
	include/utilitieslib/components/ReferenceSystem_Internal.h
	include/utilitieslib/components/RingBuffer.h
	include/utilitieslib/components/SharedHeap.h
	include/utilitieslib/components/sharedmalloc.h
	include/utilitieslib/components/SharedMemory.h
	include/utilitieslib/components/SharedQueue.h
	include/utilitieslib/components/SimpleSet.h
	include/utilitieslib/components/StashTable.h
	include/utilitieslib/components/StringCache.h
	include/utilitieslib/components/StringTable.h
	include/utilitieslib/components/TriCube/fpcube.h
	include/utilitieslib/components/TriCube/pcube.h
	include/utilitieslib/components/TriCube/vec.h
	include/utilitieslib/components/WorkerThread.h
	include/utilitieslib/language/AppLocale.h
	include/utilitieslib/language/MessageStore.h
	include/utilitieslib/language/MessageStoreUtil.h
	include/utilitieslib/language/MultiMessageStore.h
	include/utilitieslib/network/bignum.h
	include/utilitieslib/network/bindiff.h
	include/utilitieslib/network/blowfish.h
	include/utilitieslib/network/crc32c.h
	include/utilitieslib/network/crypt.h
	include/utilitieslib/network/fingerprint.h
	include/utilitieslib/network/ftpclient.h
	include/utilitieslib/network/netcomp.h
	include/utilitieslib/network/netio.h
	include/utilitieslib/network/netio_core.h
	include/utilitieslib/network/netio_receive.h
	include/utilitieslib/network/netio_send.h
	include/utilitieslib/network/netio_stats.h
	include/utilitieslib/network/NetworkSpecifier.h
	include/utilitieslib/network/net_link.h
	include/utilitieslib/network/net_linklist.h
	include/utilitieslib/network/net_masterlist.h
	include/utilitieslib/network/net_masterlistref.h
	include/utilitieslib/network/net_packet.h
	include/utilitieslib/network/net_packetutil.h
	include/utilitieslib/network/net_packet_common.h
	include/utilitieslib/network/net_socket.h
	include/utilitieslib/network/net_structdefs.h
	include/utilitieslib/network/net_typedefs.h
	include/utilitieslib/network/net_version.h
	include/utilitieslib/network/rsa.h
	include/utilitieslib/network/sock.h
	include/utilitieslib/crt.h
	include/utilitieslib/compiler.h
	include/utilitieslib/stdtypes.h
	include/utilitieslib/utilitiesLib.h
	include/utilitieslib/UtilsCXX/apcworkerpool.hpp
	include/utilitieslib/UtilsCXX/condition.hpp
	include/utilitieslib/UtilsCXX/criticalsection.hpp
	include/utilitieslib/UtilsCXX/futex.hpp
	include/utilitieslib/UtilsCXX/keyedcondition.hpp
	include/utilitieslib/UtilsCXX/list.hpp
	include/utilitieslib/UtilsCXX/listlist.hpp
	include/utilitieslib/UtilsCXX/lockingworkerpool.hpp
	include/utilitieslib/UtilsCXX/locklessworkerpool.hpp
	include/utilitieslib/UtilsCXX/nullworkerpool.hpp
	include/utilitieslib/UtilsCXX/ring.hpp
	include/utilitieslib/UtilsCXX/ringchain.hpp
	include/utilitieslib/UtilsCXX/semaphoreworkerpool.hpp
	include/utilitieslib/UtilsCXX/sleeplock.hpp
	include/utilitieslib/UtilsCXX/taskthread.hpp
	include/utilitieslib/UtilsCXX/threadedpoolallocator.hpp
	include/utilitieslib/UtilsCXX/workerpoolbase.hpp
	include/utilitieslib/UtilsNew/Array.h
	include/utilitieslib/UtilsNew/barrier.h
	include/utilitieslib/UtilsNew/Bits.h
	include/utilitieslib/UtilsNew/lock.h
	include/utilitieslib/UtilsNew/meta.h
	include/utilitieslib/UtilsNew/ncHash.h
	include/utilitieslib/UtilsNew/ncstd.h
	include/utilitieslib/UtilsNew/ncutils.h
	include/utilitieslib/UtilsNew/ntapiext.h
	include/utilitieslib/UtilsNew/profiler.h
	include/utilitieslib/UtilsNew/Str.h
	include/utilitieslib/UtilsNew/Stream.h
	include/utilitieslib/UtilsNew/timer.h
	include/utilitieslib/utils/Breakpoint.h
	include/utilitieslib/utils/Cbox.h
	include/utilitieslib/utils/cmdoldparse.h
	include/utilitieslib/utils/cmdoldparsetypes.h
	include/utilitieslib/utils/Color.h
	include/utilitieslib/utils/CommandFileParser.h
	include/utilitieslib/utils/ConsoleDebug.h
	include/utilitieslib/utils/contextQsort.h
	include/utilitieslib/utils/ConvertUtf.h
	include/utilitieslib/utils/cpu_count.h
	include/utilitieslib/utils/dds.h
	include/utilitieslib/utils/DebugState.h
	include/utilitieslib/utils/DirMonitor.h
	include/utilitieslib/utils/dobbs_hash.h
	include/utilitieslib/utils/endian.h
	include/utilitieslib/utils/error.h
	include/utilitieslib/utils/eval.h
	include/utilitieslib/utils/fastmath.h
	include/utilitieslib/utils/file.h
	include/utilitieslib/utils/fileutil.h
	include/utilitieslib/utils/fileWatch.h
	include/utilitieslib/utils/FolderCache.h
	include/utilitieslib/utils/fpmacros.h
	include/utilitieslib/utils/genericDialog.h
	include/utilitieslib/utils/hoglib.h
	include/utilitieslib/utils/hogutil.h
	include/utilitieslib/utils/LineDist.h
	include/utilitieslib/utils/ListView.h
	include/utilitieslib/utils/log.h
	include/utilitieslib/utils/mathn.h
	include/utilitieslib/utils/mathn_internal.h
	include/utilitieslib/utils/mathutil.h
	include/utilitieslib/utils/memcheck.h
	include/utilitieslib/utils/memlog.h
	include/utilitieslib/utils/MemoryMonitor.h
	include/utilitieslib/utils/memtrack.h
	include/utilitieslib/utils/mutex.h
	include/utilitieslib/utils/osdependent.h
	include/utilitieslib/utils/PigDir.h
	include/utilitieslib/utils/PigFileWrapper.h
	include/utilitieslib/utils/piglib.h
	include/utilitieslib/utils/piglib_internal.h
	include/utilitieslib/utils/prefetch.h
	include/utilitieslib/utils/process_util.h
	include/utilitieslib/utils/qsortG.h
	include/utilitieslib/utils/Quat.h
	include/utilitieslib/utils/rand.h
	include/utilitieslib/utils/RegistryReader.h
	include/utilitieslib/utils/rgb_hsv.h
	include/utilitieslib/utils/scriptvars.h
	include/utilitieslib/utils/serialize.h
	include/utilitieslib/utils/SimpleParser.h
	include/utilitieslib/utils/ssemath.h
	include/utilitieslib/utils/Stackdump.h
	include/utilitieslib/utils/strings_opt.h
	include/utilitieslib/utils/StringUtil.h
	include/utilitieslib/utils/structDefines.h
	include/utilitieslib/utils/structHist.h
	include/utilitieslib/utils/structInternals.h
	include/utilitieslib/utils/structNet.h
	include/utilitieslib/utils/structoldnames.h
	include/utilitieslib/utils/structTokenizer.h
	include/utilitieslib/utils/assert_dump.h
	include/utilitieslib/utils/SuperAssert.h
	include/utilitieslib/utils/sysutil.h
	include/utilitieslib/utils/textparser_types.h
	include/utilitieslib/utils/textparser.h
	include/utilitieslib/utils/textparserUtils.h
	include/utilitieslib/utils/tga.h
	include/utilitieslib/utils/threadedFileCopy.h
	include/utilitieslib/utils/tiff.h
	include/utilitieslib/utils/timing.h
	include/utilitieslib/utils/tokenstore.h
	include/utilitieslib/utils/UnitSpec.h
	include/utilitieslib/utils/utils.h
	include/utilitieslib/utils/winfiletime.h
	include/utilitieslib/utils/wininclude.h
	include/utilitieslib/utils/WinTabUtil.h
	include/utilitieslib/utils/winutil.h
	include/utilitieslib/version/AppRegCache.h
	include/utilitieslib/version/AppVersion.h
)

add_library(UtilitiesLib STATIC
	${UtilitiesLib_SOURCE_FILES}
	${UtilitiesLib_HEADER_FILES}
)
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/src"
	PREFIX "Source Files" FILES ${UtilitiesLib_SOURCE_FILES})
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}"
	PREFIX "Header Files" FILES ${UtilitiesLib_HEADER_FILES})

target_include_directories(UtilitiesLib PUBLIC include)
cox_target_optdebug(UtilitiesLib PUBLIC)
# Public headers retain Microsoft anonymous aggregate extensions.
set_target_properties(UtilitiesLib PROPERTIES
	C_STANDARD 11 C_STANDARD_REQUIRED ON
	CXX_STANDARD 17 CXX_STANDARD_REQUIRED ON)
if(MINGW)
	# Legacy containers share storage through typed pointers and scalars.
	target_compile_options(UtilitiesLib PUBLIC
		$<$<COMPILE_LANGUAGE:C,CXX>:-fms-extensions;-fno-strict-aliasing>)
endif()
target_compile_definitions(UtilitiesLib PRIVATE
	_CRT_SECURE_NO_WARNINGS _WINSOCK_DEPRECATED_NO_WARNINGS
	_CRT_NONSTDC_NO_DEPRECATE _LIB
	PUBLIC
	$<$<CONFIG:Debug>:FULLDEBUG;_CRTDBG_MAP_ALLOC;_DEBUG>
	$<$<CONFIG:Release>:FINAL;NDEBUG>
)
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
	target_compile_definitions(UtilitiesLib PRIVATE WIN32)
endif()
set_target_properties(UtilitiesLib PROPERTIES
	MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
if(MSVC)
	target_compile_options(UtilitiesLib PRIVATE
		/W3 /sdl /permissive- /wd4996 /wd4267
		$<$<CONFIG:Release,OptDebug>:/Gy;/Oi>)
endif()
target_link_libraries(UtilitiesLib PUBLIC
	ZLIB::ZLIB cryptopp::cryptopp CrashRpt
	iphlpapi ws2_32 winmm psapi pdh version comctl32 ole32 shell32 advapi32
	user32 gdi32 comdlg32 uuid
)
target_link_libraries(UtilitiesLib PRIVATE SparseHash::SparseHash)

include(StructParser)
StructParse(UtilitiesLib)

if(COX_BUILD_UTILITIES_TESTS)
	add_subdirectory(tests)
endif()
