#ifndef _CONTAINEREMAIL_H
#define _CONTAINEREMAIL_H

// Generated by mkproto
char *emailTemplate();
char *emailSchema();
void emailGetHeaders(int db_id);
void emailGetMessage(int db_id,int message_id);
void emailDeleteMessage(Entity* e,int message_id);
void emailHandleSendCmd(struct Entity* e, char* subj, char* recips, char* body, int influence, int type, int idx, struct ClientLink* client);
int emailGrantAttachment( Entity *e, char *attachment, int emailIndex);
int emailClaimItems( Entity *e, char * attachment, int emailIndex );
void createSystemEmail( Entity *e, char* senderName, char* subject, char* msg, int influence, char *attachment, int delaytime );

void checkPendingTransactions(Entity *e);

// End mkproto
#endif
