include(dependencies/FreeType)
include(dependencies/Glew)
include(dependencies/Jpeg)
include(dependencies/JpegCompressor)
include(dependencies/Vorbis)
include(dependencies/PhysX)
include(dependencies/NvDxt)
include(dependencies/CubeMapGen)
include(dependencies/Cg)
include(dependencies/NvParse)
include(dependencies/AlienFx)
include(dependencies/NvCpl)

set(Game_SOURCES
	../Common/account/AccountCatalog.c
	../Common/account/AccountData.c
	../Common/account/AccountInventory.c
	../Common/account/AccountTypes.cpp
	../Common/auction/Auction.c
	../Common/auction/AuctionData.c
	../Common/auction/Xact.c
	../Common/auth/auth.c
	../Common/auth/authUserData.c
	../Common/bases/basedata.c
	../Common/bases/BaseEntry.c
	../Common/bases/basefromgroup.c
	../Common/bases/baseinv.c
	../Common/bases/baselegal.c
	../Common/bases/baseparse.c
	../Common/bases/baseRaid.c
	../Common/bases/bases.c
	../Common/bases/basesend.c
	../Common/bases/basestorage.c
	../Common/bases/basesystems.c
	../Common/bases/basetogroup.c
	../Common/bases/basetrim.c
	../Common/bases/baseupkeep.c
	../Common/bases/DetailRecipe.c
	../Common/cmdparse/AppServerCmd.c
	../Common/cmdparse/cmdaccountserver.c
	../Common/cmdparse/cmdcommon.c
	../Common/container/container_store.c
	../Common/container/container_util.c
	../Common/container/dbcontainerpack.c
	../Common/DoorStrings.c
	../Common/entity/attrib_description.c
	../Common/entity/attrib_names.c
	../Common/entity/attrib_net.c
	../Common/entity/boost.c
	../Common/entity/boostset.c
	../Common/entity/buddy.c
	../Common/entity/character_attribs.c
	../Common/entity/character_base.c
	../Common/entity/character_combat_eval.c
	../Common/entity/character_eval.c
	../Common/entity/character_inventory.c
	../Common/entity/character_level.c
	../Common/entity/character_net.c
	../Common/entity/character_target.c
	../Common/entity/character_workshop.c
	../Common/entity/chatSettings.c
	../Common/entity/classes.c
	../Common/entity/Concept.c
	../Common/entity/costume.c
	../Common/entity/CustomVillainGroup.c
	../Common/entity/entity.c
	../Common/entity/entityRef.c
	../Common/entity/entStrings.c
	../Common/entity/entworldcoll.c
	../Common/entity/friendCommon.c
	../Common/entity/incarnate.c
	../Common/entity/Invention.c
	../Common/entity/LoadDefCommon.c
	../Common/entity/load_def.c
	../Common/entity/motion.c
	../Common/entity/origins.c
	../Common/entity/PCC_Critter.c
	../Common/entity/PowerInfo.c
	../Common/entity/powers.c
	../Common/entity/powers_load.c
	../Common/entity/power_customization.c
	../Common/entity/power_system.c
	../Common/entity/Proficiency.c
	../Common/entity/ragdoll.c
	../Common/entity/RewardItemType.c
	../Common/entity/RewardSlot.c
	../Common/entity/RewardToken.c
	../Common/entity/salvage.c
	../Common/entity/SgrpBasePermissions.c
	../Common/entity/Supergroup.c
	../Common/entity/supergroup_eval.c
	../Common/entity/TaskforceParams.c
	../Common/entity/teamup.c
	../Common/filter/profanity.c
	../Common/filter/titles.c
	../Common/filter/validate_name.c
	../Common/fxbhvr.c
	../Common/fxinfo.c
	../Common/gameComm/dooranimcommon.c
	../Common/gameComm/initCommon.c
	../Common/gameComm/NPC.c
	../Common/gameComm/trayCommon.c
	../Common/gameComm/VillainDef.c
	../Common/gameComm/wdwbase.c
	../Common/gameData/arenastruct.c
	../Common/gameData/BodyPart.c
	../Common/gameData/costume_data.c
	../Common/gameData/raidstruct.c
	../Common/gameData/store.c
	../Common/gameData/store_data.c
	../Common/gridcoll/ctri.c
	../Common/gridcoll/grid.c
	../Common/gridcoll/gridcache.c
	../Common/gridcoll/gridcoll.c
	../Common/gridcoll/gridcollobj.c
	../Common/gridcoll/gridfind.c
	../Common/gridcoll/gridstats.c
	../Common/gridcoll/tritri_isectline.c
	../Common/group/group.c
	../Common/group/groupdyn.c
	../Common/group/groupfilelib.c
	../Common/group/groupfileload.c
	../Common/group/groupfileloadutil.c
	../Common/group/groupfilesave.c
	../Common/group/groupgrid.c
	../Common/group/groupMetaMinimap.c
	../Common/group/groupnovodex.c
	../Common/group/groupProperties.c
	../Common/group/groupscene.c
	../Common/group/grouptrack.c
	../Common/group/grouputil.c
	../Common/imageServer.c
	../Common/language/commonLangUtil.c
	../Common/LWC_common.c
	../Common/MissionControl.c
	../Common/mission/MissionSearch.c
	../Common/mission/missionserver_meta.c
	../Common/NovodeX/NwCoreDump.cpp
	../Common/NovodeX/NwRagdoll.cpp
	../Common/NovodeX/NwSharedStream.cpp
	../Common/NovodeX/NwStream.cpp
	../Common/NovodeX/NwWrapper.cpp
	../Common/player/badges.c
	../Common/player/pmotion.c
	../Common/player/pophelp.c
	../Common/Properties.c
	../Common/seq/anim.c
	../Common/seq/AnimBitList.c
	../Common/seq/animtrack.c
	../Common/seq/animtrackanimate.c
	../Common/seq/AutoLOD.c
	../Common/seq/bones.c
	../Common/seq/gfxtree.c
	../Common/seq/modelReload.c
	../Common/seq/seq.c
	../Common/seq/seqanimate.c
	../Common/seq/seqload.c
	../Common/seq/seqregistration.c
	../Common/seq/seqsequence.c
	../Common/seq/seqskeleton.c
	../Common/seq/seqstate.c
	../Common/seq/seqtype.c
	../Common/seq/tricks.c
	../Common/storyarc/contactCommon.c
	../Common/storyarc/missiongeoCommon.c
	../Common/storyarc/missionMapCommon.c
	../Common/storyarc/playerCreatedStoryarc.c
	../Common/storyarc/playerCreatedStoryarcValidate.c
	../Common/storyarc/pnpcCommon.c
	../Common/storyarc/storyarcCommon.c
	../Common/storyarc/zowieCommon.c
	../Common/testClient/testLevelup.c
	../Common/utils/debugUtils.c
	../Common/utils/EVAL.C
	../Common/utils/Position.c
	../Common/varutils.c
	src/arena/arenagame.c
	src/bases/baseclientrecv.c
	src/bases/baseclientsend.c
	src/bases/basedrag.c
	src/bases/basedraw.c
	src/bases/baseedit.c
	src/clientcomm/authclient.c
	src/clientcomm/autoResumeInfo.c
	src/clientcomm/clientcomm.c
	src/clientcomm/clientcommreceive.c
	src/clientcomm/dbclient.c
	src/clientcomm/Des.c
	src/clientError.c
	src/Cloth/Cloth.c
	src/Cloth/ClothBuild.c
	src/Cloth/ClothCollide.c
	src/Cloth/ClothConstraint.c
	src/Cloth/ClothMesh.c
	src/Cloth/ClothMeshPrimitive.c
	src/Cloth/ClothObject.c
	src/Cloth/ClothParse.c
	src/Cloth/Wind.c
	src/cmdparse/cmdDebug.c
	src/cmdparse/cmdgame.c
	src/demo.c
	src/editorUI.c
	src/edit/ClickToSource.c
	src/edit/DebugLocation.c
	src/edit/edit.c
	src/edit/EditListView.c
	src/edit/edit_cmd.c
	src/edit/edit_cmd_adjust.c
	src/edit/edit_cmd_file.c
	src/edit/edit_cmd_group.c
	src/edit/edit_cmd_select.c
	src/edit/edit_context_menu.c
	src/edit/edit_cubemap.c
	src/edit/edit_drawlines.c
	src/edit/edit_errcheck.c
	src/edit/edit_info.c
	src/edit/edit_library.c
	src/edit/edit_lods.c
	src/edit/edit_net.c
	src/edit/edit_pickcolor.c
	src/edit/edit_select.c
	src/edit/edit_transformToolbar.c
	src/edit/edit_uiscroll.c
	src/edit/MapGenerator.c
	src/edit/Menu.c
	src/edit/UI.c
	src/entity/character_animfx_client.c
	src/entity/character_net_client.c
	src/entity/costume_client.c
	src/entity/CustomVillainGroup_Client.c
	src/entity/entclient.c
	src/entity/entDebug.c
	src/entity/entity_power_client.c
	src/entity/entrecv.c
	src/entity/PCC_Critter_Client.c
	src/entity/power_customization_client.c
	src/entity/scriptDebugClient.c
	src/formatter/smf_format.c
	src/formatter/smf_interact.c
	src/formatter/smf_main.c
	src/formatter/smf_parse.c
	src/formatter/smf_render.c
	src/formatter/smf_select.c
	src/formatter/smf_util.c
	src/game.c
	src/gameComm/chatClient.c
	src/gameComm/dooranimclient.c
	src/gameComm/initClient.c
	src/gameComm/itemselect.c
	src/gameData/costume_critter.c
	src/gameData/costume_diff.c
	src/gameData/menudef.c
	src/gameData/randomCharCreate.c
	src/gameData/randomName.c
	src/gameData/sgraidClient.c
	src/graphics/camera.c
	src/graphics/camera_detached.c
	src/graphics/clothnode.c
	src/graphics/failtext.c
	src/graphics/fog.c
	src/graphics/font.c
	src/graphics/fontdata.c
	src/graphics/frustum_c.c
	src/graphics/FX/fx.c
	src/graphics/FX/fxcapes.c
	src/graphics/FX/fxdebris.c
	src/graphics/FX/fxfluid.c
	src/graphics/FX/fxgeo.c
	src/graphics/FX/fxlists.c
	src/graphics/FX/fxutil.c
	src/graphics/FX/particle.c
	src/graphics/gfx.c
	src/graphics/gfxDebug.c
	src/graphics/gfxDevHUD.c
	src/graphics/gfxLoadScreens.c
	src/graphics/gfxSettings.c
	src/graphics/gfxwindow.c
	src/graphics/groupdraw.c
	src/graphics/groupdrawinline.c
	src/graphics/groupdrawutil.c
	src/graphics/groupMiniTrackers.c
	src/graphics/groupThumbnail.c
	src/graphics/imageCapture.c
	src/graphics/jpeg.cpp
	src/graphics/light.c
	src/graphics/seqgraphics.c
	src/graphics/splat.c
	src/graphics/sun.c
	src/graphics/textureatlas.c
	src/graphics/truetype/ttAppleMapping.c
	src/graphics/truetype/ttDebug.c
	src/graphics/truetype/ttFontBitmap.c
	src/graphics/truetype/ttFontCore.c
	src/graphics/truetype/ttFontDraw.c
	src/graphics/truetype/ttFontManager.c
	src/graphics/ttFont.c
	src/graphics/ttFontUtil.c
	src/graphics/viewport.c
	src/graphics/view_cache.c
	src/graphics/vistray.c
	src/graphics/vistraygrid.c
	src/graphics/zOcclusion.c
	src/graphics/zOcclusionClip.c
	src/group/groupdynrecv.c
	src/group/groupnetrecv.c
	src/language/langClientUtil.c
	src/LWC.c
	src/main.c
	src/player/badges_client.c
	src/player/inventory_client.c
	src/player/player.c
	src/player/playerState.c
	src/player/playerSticky.c
	src/render/bump.c
	src/render/cubemap.c
	src/render/cubemap_filter.cpp
	src/render/dxtlibwrapper.cpp
	src/render/model.c
	src/render/model_cache.c
	src/render/pbuffer.c
	src/render/perfcounter.c
	src/render/renderbonedmodel.c
	src/render/rendercloth.c
	src/render/renderEffects.c
	src/render/renderfont.c
	src/render/rendermodel.c
	src/render/renderparticles.c
	src/render/renderperf.c
	src/render/renderprim.c
	src/render/rendershadow.c
	src/render/rendershadowmap.c
	src/render/renderssao.c
	src/render/renderstats.c
	src/render/rendertree.c
	src/render/rendertricks.c
	src/render/renderUtil.c
	src/render/renderWater.c
	src/render/rotoZoom.c
	src/render/sprite.c
	src/render/tex.c
	src/render/texUnload.c
	src/render/texWords.c
	src/render/texWordsEdit.c
	src/render/tex_gen.c
	src/render/thread/glext.c
	src/render/thread/mipmap.c
	src/render/thread/rt_bonedmodel.c
	src/render/thread/rt_cgfx.c
	src/render/thread/rt_cgfx_statemgmt.c
	src/render/thread/rt_cloth.c
	src/render/thread/rt_cubemap.c
	src/render/thread/rt_cursor.c
	src/render/thread/rt_effects.c
	src/render/thread/rt_filter.c
	src/render/thread/rt_font.c
	src/render/thread/rt_graphfps.c
	src/render/thread/rt_init.c
	src/render/thread/rt_model.c
	src/render/thread/rt_model_cache.c
	src/render/thread/rt_particles.c
	src/render/thread/rt_pbuffer.c
	src/render/thread/rt_perf.c
	src/render/thread/rt_prim.c
	src/render/thread/rt_queue.c
	src/render/thread/rt_report.c
	src/render/thread/rt_shaderMgr.c
	src/render/thread/rt_shadow.c
	src/render/thread/rt_shadowmap.c
	src/render/thread/rt_sprite.c
	src/render/thread/rt_ssao.c
	src/render/thread/rt_state.c
	src/render/thread/rt_stats.c
	src/render/thread/rt_tex.c
	src/render/thread/rt_tricks.c
	src/render/thread/rt_tune.c
	src/render/thread/rt_util.c
	src/render/thread/rt_water.c
	src/render/thread/rt_win_init.c
	src/render/thread/shadersATI.c
	src/render/thread/shadersTexEnv.c
	src/render/thread/wcw_statemgmt.c
	src/render/videoMemory.cpp
	src/sound/ogg_decode.c
	src/sound/sound.c
	src/sound/sound_ambient.c
	src/sound/sound_sys.c
	src/storyarc/contactClient.c
	src/storyarc/missionClient.c
	src/storyarc/playerCreatedStoryarcClient.c
	src/storyarc/storyarcClient.c
	src/storyarc/zowieClient.c
	src/uiLevelingpact.c
	src/uiTextLink.c
	src/UI/Hybrid/uiArchetype.c
	src/UI/Hybrid/uiBody.c
	src/UI/Hybrid/uiCostumes.c
	src/UI/Hybrid/uiHybridMenu.c
	src/UI/Hybrid/uiLoyaltyTree.c
	src/UI/Hybrid/uiLoyaltyTreeAccess.c
	src/UI/Hybrid/uiLWC.c
	src/UI/Hybrid/uiOrigin.c
	src/UI/Hybrid/uiPlaystyle.c
	src/UI/Hybrid/uiPower.c
	src/UI/Hybrid/uiRedirect.c
	src/UI/Hybrid/uiRegister.c
	src/UI/Hybrid/uiWebStoreFrame.c
	src/UI/sprite/sprite_base.c
	src/UI/sprite/sprite_debug.c
	src/UI/sprite/sprite_font.c
	src/UI/sprite/sprite_list.c
	src/UI/sprite/sprite_text.c
	src/UI/uiAmountSlider.c
	src/UI/uiArena.c
	src/UI/uiArenaGladiator.c
	src/UI/uiArenaJoin.c
	src/UI/uiArenaList.c
	src/UI/uiArenaResult.c
	src/UI/uiAuction.c
	src/UI/uiAutomap.c
	src/UI/uiAutomapFog.c
	src/UI/uiAvatar.c
	src/UI/uiBadges.c
	src/UI/uiBaseInput.c
	src/UI/uiBaseInventory.c
	src/UI/uiBaseLog.c
	src/UI/uiBaseProps.c
	src/UI/uiBaseRoom.c
	src/UI/uiBaseStorage.c
	src/UI/uiBox.c
	src/UI/uiBrowser.c
	src/UI/uiBuff.c
	src/UI/uiChannel.c
	src/UI/uiChannelSearch.c
	src/UI/uiChat.c
	src/UI/uiChatOptions.c
	src/UI/uiChatUtil.c
	src/UI/uiClipper.c
	src/UI/uiClue.c
	src/UI/uiColorPicker.c
	src/UI/uiCombatMonitor.c
	src/UI/uiCombatNumbers.c
	src/UI/uiCombineSpec.c
	src/UI/uiComboBox.c
	src/UI/uiComment.c
	src/UI/uiCompass.c
	src/UI/uiConceptInv.c
	src/UI/uiConsole.c
	src/UI/uiContact.c
	src/UI/uiContactDialog.c
	src/UI/uiContactFinder.c
	src/UI/uiContextMenu.c
	src/UI/uiConvertEnhancement.c
	src/UI/uiCostume.c
	src/UI/uiCostumeSelect.c
	src/UI/uiCursor.c
	src/UI/uiCustomVillainGroupWindow.c
	src/UI/uiCustomWindow.c
	src/UI/uiDeath.c
	src/UI/uiDialog.c
	src/UI/uiDock.c
	src/UI/UIEdit.c
	src/UI/uiEditText.c
	src/UI/uiEmail.c
	src/UI/uiEmote.c
	src/UI/uiEnhancement.c
	src/UI/uiFocus.c
	src/UI/uiFriend.c
	src/UI/uiFx.c
	src/UI/uiGame.c
	src/UI/uiGender.c
	src/UI/uiGift.c
	src/UI/uiGroupWindow.c
	src/UI/uiGrowBig.c
	src/UI/uiHelp.c
	src/UI/uiHelpButton.c
	src/UI/uiIME.c
	src/UI/uiIncarnate.c
	src/UI/uiInfo.c
	src/UI/uiInput.c
	src/UI/uiInspiration.c
	src/UI/uiInvent.c
	src/UI/uiInventory.c
	src/UI/uiKeybind.c
	src/UI/uiKeymapping.c
	src/UI/uiLeague.c
	src/UI/uiLevelPower.c
	src/UI/uiLevelSpec.c
	src/UI/uiLfg.c
	src/UI/uiListView.c
	src/UI/uiLoadCostume.c
	src/UI/uiLoadingTip.c
	src/UI/uiLoadPowerCust.c
	src/UI/uiLogin.c
	src/UI/uiMapSelect.c
	src/UI/uiMission.c
	src/UI/uiMissionComment.c
	src/UI/uiMissionMaker.c
	src/UI/uiMissionMakerScrollSet.c
	src/UI/uiMissionReview.c
	src/UI/uiMissionSearch.c
	src/UI/uiMissionSummary.c
	src/UI/uiMMMapViewer.c
	src/UI/uiNet.c
	src/UI/uiNewFeatures.c
	src/UI/uiNPCCostume.c
	src/UI/uiNPCCreationNLM.c
	src/UI/uiNPCProfile.c
	src/UI/uiOptions.c
	src/UI/uiPCCCreationNLM.c
	src/UI/uiPCCPowers.c
	src/UI/uiPCCProfile.c
	src/UI/uiPCCRank.c
	src/UI/uiPet.c
	src/UI/uiPetition.c
	src/UI/uiPictureBrowser.c
	src/UI/uiPlaque.c
	src/UI/uiPlayerNote.c
	src/UI/uiPopHelp.c
	src/UI/uiPowerCust.c
	src/UI/uiPowerInfo.c
	src/UI/uiPowerInventory.c
	src/UI/uiPowers.c
	src/UI/uiQuit.c
	src/UI/uiRaidResult.c
	src/UI/uiRecentTeam.c
	src/UI/uiRecipeInv.c
	src/UI/uiRecipeInventory.c
	src/UI/uiRenderStats.c
	src/UI/uiReSpec.c
	src/UI/uiReticle.c
	src/UI/uiRewardChoice.c
	src/UI/uiSalvage.c
	src/UI/uiSalvageOpen.c
	src/UI/uiSaveCostume.c
	src/UI/uiScript.c
	src/UI/uiScrollBar.c
	src/UI/uiScrollSelector.c
	src/UI/uiScrollSet.c
	src/UI/uiServerTransfer.c
	src/UI/uiSGList.c
	src/UI/uiSGRaidList.c
	src/UI/uiSlider.c
	src/UI/uiSMFView.c
	src/UI/uiStatus.c
	src/UI/uiStore.c
	src/UI/uiStoredSalvage.c
	src/UI/uiSupercostume.c
	src/UI/uiSupergroup.c
	src/UI/uiSuperRegistration.c
	src/UI/uiTabControl.c
	src/UI/uiTailor.c
	src/UI/uiTarget.c
	src/UI/uiTeam.c
	src/UI/uiTitleSelect.c
	src/UI/uiToolTip.c
	src/UI/uiTrade.c
	src/UI/uiTradeLogic.c
	src/UI/uiTray.c
	src/UI/uiTraySingle.c
	src/UI/uiTree.c
	src/UI/uiTrialReminder.c
	src/UI/uiTurnstile.c
	src/UI/uiUtil.c
	src/UI/uiUtilGame.c
	src/UI/uiUtilMenu.c
	src/UI/uiWindows.c
	src/UI/uiWindows_init.c
	src/validateFiles.c
	src/win/hwlight.c
	src/win/input.c
	src/win/win_cursor.c
	src/win/win_init.c
)

set(Game_HEADERS
	../Common/account/AccountCatalog.h
	../Common/account/AccountData.h
	../Common/account/AccountInventory.h
	../Common/account/AccountTypes.h
	../Common/auction/Auction.h
	../Common/auction/AuctionData.h
	../Common/auction/Xact.h
	../Common/auth/auth.h
	../Common/auth/authconn.h
	../Common/auth/authUserData.h
	../Common/bases/basedata.h
	../Common/bases/basefromgroup.h
	../Common/bases/baseinv.h
	../Common/bases/baselegal.h
	../Common/bases/baseparse.h
	../Common/bases/baseRaid.h
	../Common/bases/bases.h
	../Common/bases/basesend.h
	../Common/bases/basestorage.h
	../Common/bases/basesystems.h
	../Common/bases/basetogroup.h
	../Common/bases/basetrim.h
	../Common/bases/baseupkeep.h
	../Common/bases/DetailRecipe.h
	../Common/chatdb.h
	../Common/ClickToSourceFlags.h
	../Common/cmdparse/AppServerCmd.h
	../Common/cmdparse/cmdaccountserver.h
	../Common/cmdparse/cmdcommon.h
	../Common/cmdparse/cmdcommon_enum.h
	../Common/cmdparse/cmdcontrols.h
	../Common/comm_backend.h
	../Common/comm_game.h
	../Common/container/container_store.h
	../Common/container/container_util.h
	../Common/container/dbcontainerpack.h
	../Common/DoorStrings.h
	../Common/entity/attrib_description.h
	../Common/entity/attrib_names.h
	../Common/entity/attrib_net.h
	../Common/entity/boost.h
	../Common/entity/boostset.h
	../Common/entity/buddy.h
	../Common/entity/character_attribs.h
	../Common/entity/character_base.h
	../Common/entity/character_combat_eval.h
	../Common/entity/character_eval.h
	../Common/entity/character_inventory.h
	../Common/entity/character_level.h
	../Common/entity/character_net.h
	../Common/entity/character_target.h
	../Common/entity/character_workshop.h
	../Common/entity/chatSettings.h
	../Common/entity/classes.h
	../Common/entity/Concept.h
	../Common/entity/costume.h
	../Common/entity/CustomVillainGroup.h
	../Common/entity/entity.h
	../Common/entity/entityRef.h
	../Common/entity/entPlayer.h
	../Common/entity/entStrings.h
	../Common/entity/entVarUpdate.h
	../Common/entity/entworldcoll.h
	../Common/entity/friendCommon.h
	../Common/entity/incarnate.h
	../Common/entity/Invention.h
	../Common/entity/LoadDefCommon.h
	../Common/entity/load_def.h
	../Common/entity/motion.h
	../Common/entity/netfx.h
	../Common/entity/origins.h
	../Common/entity/PCC_Critter.h
	../Common/entity/PowerInfo.h
	../Common/entity/powers.h
	../Common/entity/power_customization.h
	../Common/entity/power_system.h
	../Common/entity/Proficiency.h
	../Common/entity/ragdoll.h
	../Common/entity/RewardItemType.h
	../Common/entity/RewardSlot.h
	../Common/entity/RewardToken.h
	../Common/entity/salvage.h
	../Common/entity/SgrpBasePermissions.h
	../Common/entity/SgrpStatsCommon.h
	../Common/entity/Supergroup.h
	../Common/entity/supergroup_eval.h
	../Common/entity/TaskforceParams.h
	../Common/entity/teamup.h
	../Common/entity/TokenizerUiWidget.h
	../Common/filter/profanity.h
	../Common/filter/titles.h
	../Common/filter/validate_name.h
	../Common/fxbhvr.h
	../Common/fxinfo.h
	../Common/fxutil.h
	../Common/gameComm/debugCommon.h
	../Common/gameComm/dooranimcommon.h
	../Common/gameComm/initCommon.h
	../Common/gameComm/Npc.h
	../Common/gameComm/petCommon.h
	../Common/gameComm/trayCommon.h
	../Common/gameComm/VillainDef.h
	../Common/gameComm/wdwbase.h
	../Common/gameData/arenastruct.h
	../Common/gameData/BodyPart.h
	../Common/gameData/costume_data.h
	../Common/gameData/raidstruct.h
	../Common/gameData/store.h
	../Common/gameData/store_data.h
	../Common/gridcoll/ctri.h
	../Common/gridcoll/grid.h
	../Common/gridcoll/gridcache.h
	../Common/gridcoll/gridcoll.h
	../Common/gridcoll/gridcollobj.h
	../Common/gridcoll/gridcollperftest.h
	../Common/gridcoll/gridfind.h
	../Common/gridcoll/tritri_isectline.h
	../Common/group/group.h
	../Common/group/groupdyn.h
	../Common/group/groupfilelib.h
	../Common/group/groupfileload.h
	../Common/group/groupfileloadutil.h
	../Common/group/groupfilesave.h
	../Common/group/groupgrid.h
	../Common/group/groupMetaMinimap.h
	../Common/group/groupnovodex.h
	../Common/group/groupProperties.h
	../Common/group/groupscene.h
	../Common/group/grouptrack.h
	../Common/group/grouputil.h
	../Common/imageServer.h
	../Common/language/commonLangUtil.h
	../Common/LWC_common.h
	../Common/MissionControl.h
	../Common/mission/MissionSearch.h
	../Common/mission/missionserver_meta.h
	../Common/NovodeX/NwCoreDump.h
	../Common/NovodeX/NwRagdoll.h
	../Common/NovodeX/NwSharedStream.h
	../Common/NovodeX/NwStream.h
	../Common/NovodeX/NwTypes.h
	../Common/NovodeX/NwWrapper.h
	../Common/player/badges.h
	../Common/player/pmotion.h
	../Common/player/pophelp.h
	../Common/Properties.h
	../Common/seq/anim.h
	../Common/seq/AnimBitList.h
	../Common/seq/animtrack.h
	../Common/seq/animtrackanimate.h
	../Common/seq/AutoLOD.h
	../Common/seq/bones.h
	../Common/seq/gfxtree.h
	../Common/seq/modelReload.h
	../Common/seq/seq.h
	../Common/seq/seqanimate.h
	../Common/seq/seqload.h
	../Common/seq/seqregistration.h
	../Common/seq/seqsequence.h
	../Common/seq/seqskeleton.h
	../Common/seq/seqstate.h
	../Common/seq/seqtype.h
	../Common/seq/tricks.h
	../Common/storyarc/contactCommon.h
	../Common/storyarc/missiongeoCommon.h
	../Common/storyarc/missionMapCommon.h
	../Common/storyarc/playerCreatedStoryarc.h
	../Common/storyarc/playerCreatedStoryarcTypes.h
	../Common/storyarc/playerCreatedStoryarcValidate.h
	../Common/storyarc/pnpcCommon.h
	../Common/storyarc/storyarcCommon.h
	../Common/storyarc/zowieCommon.h
	../Common/testClient/TestClient.h
	../Common/testClient/testLevelup.h
	../Common/utils/debugUtils.h
	../Common/utils/position.h
	../Common/varutils.h
	src/arena/arenagame.h
	src/bases/baseclientrecv.h
	src/bases/baseclientsend.h
	src/bases/basedraw.h
	src/bases/baseedit.h
	src/clientcomm/authclient.h
	src/clientcomm/autoResumeInfo.h
	src/clientcomm/clientcomm.h
	src/clientcomm/clientcommreceive.h
	src/clientcomm/dbclient.h
	src/clientcomm/Des.h
	src/clientError.h
	src/Cloth/Cloth.h
	src/Cloth/ClothCollide.h
	src/Cloth/ClothDefs.h
	src/Cloth/ClothMesh.h
	src/Cloth/ClothPrivate.h
	src/Cloth/Wind.h
	src/cmdparse/cmdDebug.h
	src/cmdparse/cmdgame.h
	src/demo.h
	src/editorUI.h
	src/edit/ClickToSource.h
	src/edit/DebugLocation.h
	src/edit/edit.h
	src/edit/EditListView.h
	src/edit/edit_cmd.h
	src/edit/edit_cmd_adjust.h
	src/edit/edit_cmd_file.h
	src/edit/edit_cmd_group.h
	src/edit/edit_cmd_select.h
	src/edit/edit_context_menu.h
	src/edit/edit_cubemap.h
	src/edit/edit_drawlines.h
	src/edit/edit_errcheck.h
	src/edit/edit_info.h
	src/edit/edit_library.h
	src/edit/edit_lods.h
	src/edit/edit_net.h
	src/edit/edit_pickcolor.h
	src/edit/edit_select.h
	src/edit/edit_transformToolbar.h
	src/edit/edit_uiscroll.h
	src/edit/MapGenerator.h
	src/edit/Menu.h
	src/edit/UI.h
	src/entity/character_animfx_client.h
	src/entity/character_net_client.h
	src/entity/costume_client.h
	src/entity/CustomVillainGroup_Client.h
	src/entity/entclient.h
	src/entity/entDebug.h
	src/entity/entDebugPrivate.h
	src/entity/entIncludeClient.h
	src/entity/entity_power_client.h
	src/entity/entrecv.h
	src/entity/PCC_Critter_Client.h
	src/entity/power_customization_client.h
	src/entity/scriptDebugClient.h
	src/formatter/smf_format.h
	src/formatter/smf_interact.h
	src/formatter/smf_main.h
	src/formatter/smf_parse.h
	src/formatter/smf_render.h
	src/formatter/smf_select.h
	src/formatter/smf_util.h
	src/game.h
	src/gameComm/chatClient.h
	src/gameComm/dooranimclient.h
	src/gameComm/initClient.h
	src/gameComm/itemselect.h
	src/gameData/costume_critter.h
	src/gameData/costume_diff.h
	src/gameData/list1a.h
	src/gameData/list2a.h
	src/gameData/menudef.h
	src/gameData/randomCharCreate.h
	src/gameData/randomName.h
	src/gameData/sgraidClient.h
	src/graphics/camera.h
	src/graphics/clothnode.h
	src/graphics/failtext.h
	src/graphics/fog.h
	src/graphics/font.h
	src/graphics/fontdata.h
	src/graphics/frustum_c.h
	src/graphics/FX/fx.h
	src/graphics/FX/fxcapes.h
	src/graphics/FX/fxdebris.h
	src/graphics/FX/fxfluid.h
	src/graphics/FX/fxgeo.h
	src/graphics/FX/fxlists.h
	src/graphics/FX/particle.h
	src/graphics/gfx.h
	src/graphics/gfxDebug.h
	src/graphics/gfxDevHUD.h
	src/graphics/gfxLoadScreens.h
	src/graphics/gfxSettings.h
	src/graphics/gfxwindow.h
	src/graphics/groupdraw.h
	src/graphics/groupdrawinline.h
	src/graphics/groupdrawutil.h
	src/graphics/groupMiniTrackers.h
	src/graphics/groupThumbnail.h
	src/graphics/imageCapture.h
	src/graphics/jpeg.h
	src/graphics/light.h
	src/graphics/seqgraphics.h
	src/graphics/splat.h
	src/graphics/sun.h
	src/graphics/test_cape.h
	src/graphics/test_flag.h
	src/graphics/textureatlas.h
	src/graphics/textureatlasPrivate.h
	src/graphics/truetype/ttAppleMapping.h
	src/graphics/truetype/ttDebug.h
	src/graphics/truetype/ttFontBitmap.h
	src/graphics/truetype/ttFontCore.h
	src/graphics/truetype/ttFontDraw.h
	src/graphics/truetype/ttFontManager.h
	src/graphics/ttFont.h
	src/graphics/ttFontUtil.h
	src/graphics/viewport.h
	src/graphics/view_cache.h
	src/graphics/vistray.h
	src/graphics/vistraygrid.h
	src/graphics/zOcclusion.h
	src/graphics/zOcclusionClip.h
	src/graphics/zOcclusionDraw.h
	src/graphics/zOcclusionTypes.h
	src/group/groupdynrecv.h
	src/group/groupnetrecv.h
	src/language/langClientUtil.h
	src/LWC.h
	src/player/badges_client.h
	src/player/inventory_client.h
	src/player/player.h
	src/player/playerState.h
	src/player/playerSticky.h
	src/render/bump.h
	src/render/cubemap.h
	src/render/cubemap_filter.h
	src/render/dd.h
	src/render/dxtlibwrapper.h
	src/render/model.h
	src/render/model_cache.h
	src/render/pbuffer.h
	src/render/perfcounter.h
	src/render/render.h
	src/render/renderbonedmodel.h
	src/render/rendercgfx.h
	src/render/rendercloth.h
	src/render/renderEffects.h
	src/render/renderfont.h
	src/render/rendermodel.h
	src/render/renderparticles.h
	src/render/renderperf.h
	src/render/renderprim.h
	src/render/rendershadow.h
	src/render/rendershadowmap.h
	src/render/renderssao.h
	src/render/renderstats.h
	src/render/rendertree.h
	src/render/rendertricks.h
	src/render/renderUtil.h
	src/render/renderWater.h
	src/render/rotoZoom.h
	src/render/sprite.h
	src/render/tex.h
	src/render/texEnums.h
	src/render/texUnload.h
	src/render/texWords.h
	src/render/texWordsEdit.h
	src/render/texWordsPrivate.h
	src/render/tex_gen.h
	src/render/thread/mipmap.h
	src/render/thread/nvparse.h
	src/render/thread/ogl.h
	src/render/thread/rt_bonedmodel.h
	src/render/thread/rt_cgfx.h
	src/render/thread/rt_cgfx_statemgmt.h
	src/render/thread/rt_cloth.h
	src/render/thread/rt_cubemap.h
	src/render/thread/rt_cursor.h
	src/render/thread/rt_effects.h
	src/render/thread/rt_filter.h
	src/render/thread/rt_font.h
	src/render/thread/rt_init.h
	src/render/thread/rt_model.h
	src/render/thread/rt_model_cache.h
	src/render/thread/rt_particles.h
	src/render/thread/rt_pbuffer.h
	src/render/thread/rt_perf.h
	src/render/thread/rt_prim.h
	src/render/thread/rt_queue.h
	src/render/thread/rt_report.h
	src/render/thread/rt_shaderMgr.h
	src/render/thread/rt_shadow.h
	src/render/thread/rt_shadowmap.h
	src/render/thread/rt_sprite.h
	src/render/thread/rt_ssao.h
	src/render/thread/rt_state.h
	src/render/thread/rt_stats.h
	src/render/thread/rt_tex.h
	src/render/thread/rt_tricks.h
	src/render/thread/rt_tune.h
	src/render/thread/rt_util.h
	src/render/thread/rt_water.h
	src/render/thread/rt_win_init.h
	src/render/thread/shadersATI.h
	src/render/thread/shadersTexEnv.h
	src/render/thread/wcw_statemgmt.h
	src/render/videoMemory.h
	src/resource.h
	src/sound/ogg_decode.h
	src/sound/sound.h
	src/sound/sound_ambient.h
	src/sound/sound_sys.h
	src/storyarc/contactClient.h
	src/storyarc/missionClient.h
	src/storyarc/playerCreatedStoryarcClient.h
	src/storyarc/storyarcClient.h
	src/storyarc/zowieClient.h
	src/uiLevelingpact.h
	src/UI/Hybrid/uiArchetype.h
	src/UI/Hybrid/uiBody.h
	src/UI/Hybrid/uiCostumes.h
	src/UI/Hybrid/uiHybridMenu.h
	src/UI/Hybrid/uiLoyaltyTree.h
	src/UI/Hybrid/uiLoyaltyTreeAccess.h
	src/UI/Hybrid/uiLWC.h
	src/UI/Hybrid/uiOrigin.h
	src/UI/Hybrid/uiPlaystyle.h
	src/UI/Hybrid/uiPower.h
	src/UI/Hybrid/uiRedirect.h
	src/UI/Hybrid/uiRegister.h
	src/UI/Hybrid/uiWebStoreFrame.h
	src/UI/sprite/sprite_base.h
	src/UI/sprite/sprite_debug.h
	src/UI/sprite/sprite_font.h
	src/UI/sprite/sprite_list.h
	src/UI/sprite/sprite_text.h
	src/UI/uiAmountSlider.h
	src/UI/uiArena.h
	src/UI/uiArenaGladiator.h
	src/UI/uiArenaJoin.h
	src/UI/uiArenaList.h
	src/UI/uiArenaResult.h
	src/UI/uiAuction.h
	src/UI/uiAutomap.h
	src/UI/uiAutomapFog.h
	src/UI/uiAvatar.h
	src/UI/uiBadges.h
	src/UI/uiBaseInput.h
	src/UI/uiBaseInventory.h
	src/UI/uiBaseLog.h
	src/UI/uiBaseProps.h
	src/UI/uiBaseRoom.h
	src/UI/uiBaseStorage.h
	src/UI/uiBox.h
	src/UI/uiBrowser.h
	src/UI/uiBuff.h
	src/UI/uiChannel.h
	src/UI/uiChannelSearch.h
	src/UI/uiChat.h
	src/UI/uiChatOptions.h
	src/UI/uiChatUtil.h
	src/UI/uiClipper.h
	src/UI/uiClue.h
	src/UI/uiColorPicker.h
	src/UI/uiCombatMonitor.h
	src/UI/uiCombatNumbers.h
	src/UI/uiCombineSpec.h
	src/UI/uiComboBox.h
	src/UI/uiComment.h
	src/UI/uiCompass.h
	src/UI/uiConceptInv.h
	src/UI/uiConsole.h
	src/UI/uiContact.h
	src/UI/uiContactDialog.h
	src/UI/uiContactFinder.h
	src/UI/uiContextMenu.h
	src/UI/uiConvertEnhancement.h
	src/UI/uiCostume.h
	src/UI/uiCostumeSelect.h
	src/UI/uiCursor.h
	src/UI/uiCustomVillainGroupWindow.h
	src/UI/uiCustomWindow.h
	src/UI/uiDeath.h
	src/UI/uiDialog.h
	src/UI/uiDock.h
	src/UI/UIEdit.h
	src/UI/uiEditText.h
	src/UI/uiEmail.h
	src/UI/uiEmote.h
	src/UI/uiEnhancement.h
	src/UI/uiFocus.h
	src/UI/uiFriend.h
	src/UI/uiFx.h
	src/UI/uiGame.h
	src/UI/uiGender.h
	src/UI/uiGift.h
	src/UI/uiGroupWindow.h
	src/UI/uiGrowBig.h
	src/UI/uiHelp.h
	src/UI/uiHelpButton.h
	src/UI/uiIME.h
	src/UI/uiIncarnate.h
	src/UI/uiInclude.h
	src/UI/uiInfo.h
	src/UI/uiInput.h
	src/UI/uiInspiration.h
	src/UI/uiInvent.h
	src/UI/uiInventory.h
	src/UI/uiKeybind.h
	src/UI/uiKeymapping.h
	src/UI/uiLeague.h
	src/UI/uiLevelPower.h
	src/UI/uiLevelSpec.h
	src/UI/uiLfg.h
	src/UI/uiListView.h
	src/UI/uiLoadCostume.h
	src/UI/uiLoadingTip.h
	src/UI/uiLoadPowerCust.h
	src/UI/uiLogin.h
	src/UI/uiMapSelect.h
	src/UI/uiMission.h
	src/UI/uiMissionComment.h
	src/UI/uiMissionMaker.h
	src/UI/uiMissionMakerScrollSet.h
	src/UI/uiMissionReview.h
	src/UI/uiMissionSearch.h
	src/UI/uiMissionSummary.h
	src/UI/uiMMMapViewer.h
	src/UI/uiNet.h
	src/UI/uiNewFeatures.h
	src/UI/uiNPCCostume.h
	src/UI/uiNPCCreationNLM.h
	src/UI/uiNPCProfile.h
	src/UI/uiOptions.h
	src/UI/uiPCCCreationNLM.h
	src/UI/uiPCCPowers.h
	src/UI/uiPCCProfile.h
	src/UI/uiPCCRank.h
	src/UI/uiPet.h
	src/UI/uiPetition.h
	src/UI/uiPictureBrowser.h
	src/UI/uiPlaque.h
	src/UI/uiPlayerNote.h
	src/UI/uiPopHelp.h
	src/UI/uiPowerCust.h
	src/UI/uiPowerInfo.h
	src/UI/uiPowerInventory.h
	src/UI/uiPowers.h
	src/UI/uiQuit.h
	src/UI/uiRaidResult.h
	src/UI/uiRecentTeam.h
	src/UI/uiRecipeInv.h
	src/UI/uiRecipeInventory.h
	src/UI/uiRenderStats.h
	src/UI/uiReSpec.h
	src/UI/uiReticle.h
	src/UI/uiRewardChoice.h
	src/UI/uiSalvage.h
	src/UI/uiSalvageOpen.h
	src/UI/uiSaveCostume.h
	src/UI/uiScript.h
	src/UI/uiScrollBar.h
	src/UI/uiScrollSelector.h
	src/UI/uiScrollSet.h
	src/UI/uiServerTransfer.h
	src/UI/uiSGList.h
	src/UI/uiSGRaidList.h
	src/UI/uiSlider.h
	src/UI/uiSMFView.h
	src/UI/uiStatus.h
	src/UI/uiStore.h
	src/UI/uiStoredSalvage.h
	src/UI/uiSupercostume.h
	src/UI/uiSupergroup.h
	src/UI/uiSuperRegistration.h
	src/UI/uiTabControl.h
	src/UI/uiTailor.h
	src/UI/uiTarget.h
	src/UI/uiTeam.h
	src/UI/uiTextLink.h
	src/UI/uiTitleSelect.h
	src/UI/uiToolTip.h
	src/UI/uiTrade.h
	src/UI/uiTradeLogic.h
	src/UI/uiTray.h
	src/UI/uiTraySingle.h
	src/UI/uiTree.h
	src/UI/uiTrialReminder.h
	src/UI/uiTurnstile.h
	src/UI/uiUtil.h
	src/UI/uiUtilGame.h
	src/UI/uiUtilMenu.h
	src/UI/uiWindows.h
	src/UI/uiWindows_init.h
	src/win/hwlight.h
	src/win/input.h
	src/win/win_cursor.h
	src/win/win_init.h
)

set(Game_RESOURCES
	src/resource.rc
)

set(Game_IMAGES
	src/CrypticIcn.ico
	src/Icon_Cov.ico
	src/Icon_Korean.ico
	src/Icon_Rogue.ico
	src/Icon_Statesman.ico
	src/logo4small.bmp
	src/logo4small_red.bmp
	src/logo4small_rogue.bmp
)

# Game owns the parser tables included by its client and Common sources.
# Included .c files are byproducts, not separate translation units.
set(Game_GENERATED
	src/AutoGen/bones_h_ast.c
	src/AutoGen/bones_h_ast.h
	src/AutoGen/groupMetaMinimap_h_ast.c
	src/AutoGen/groupMetaMinimap_h_ast.h
	src/AutoGen/MissionSearch_h_ast.c
	src/AutoGen/MissionSearch_h_ast.h
	src/AutoGen/playerCreatedStoryarcTypes_h_ast.c
	src/AutoGen/playerCreatedStoryarcTypes_h_ast.h
	src/AutoGen/playerCreatedStoryarcValidate_h_ast.c
	src/AutoGen/playerCreatedStoryarcValidate_h_ast.h
	src/AutoGen/uiMissionComment_c_ast.c
	src/AutoGen/uiMissionComment_c_ast.h
	src/AutoGen/uiMissionMakerScrollSet_h_ast.c
	src/AutoGen/uiMissionMakerScrollSet_h_ast.h
	src/AutoGen/uiScrollSet_h_ast.c
	src/AutoGen/uiScrollSet_h_ast.h
)

# StructParser always emits these files, but the original project does not
# compile them. The Game-specific names give each output one build owner.
list(APPEND Game_GENERATED
	src/AutoGen/Game_AutoTest.c
	src/AutoGen/Game_autogen_QueuedFuncs.c
	src/AutoGen/Game_autogen_QueuedFuncs.h
	src/AutoGen/Game_autorun_autogen.cpp
	src/AutoGen/Game_autorun_extrafunc_autogen.c
	src/AutoGen/Game_autotransactions_autogen.c
	src/AutoGen/Game_commands_autogen.c
	src/AutoGen/Game_commands_autogen_CommandFuncs.c
	src/AutoGen/Game_commands_autogen_CommandFuncs.h
	src/AutoGen/Game_latelink_autogen.c
	../Common/AutoGen/Game_autogen_RemoteFuncs.c
	../Common/AutoGen/Game_autogen_RemoteFuncs.h
	../Common/AutoGen/Game_autogen_SlowFuncs.c
	../Common/AutoGen/Game_autogen_SlowFuncs.h
)
set_source_files_properties(${Game_GENERATED} PROPERTIES
	GENERATED TRUE HEADER_FILE_ONLY TRUE)

add_executable(Game WIN32
	${Game_SOURCES} ${Game_HEADERS} ${Game_RESOURCES} ${Game_IMAGES}
	${Game_GENERATED})
source_group(TREE "${PROJECT_SOURCE_DIR}" FILES
	${Game_SOURCES} ${Game_HEADERS} ${Game_RESOURCES} ${Game_IMAGES}
	${Game_GENERATED})
# CMake interprets the uppercase extension as C++; this is legacy C code.
set_source_files_properties(../Common/utils/EVAL.C PROPERTIES LANGUAGE C)
cox_target_defaults(Game)
set_target_properties(Game PROPERTIES
	MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>"
	OUTPUT_NAME "CityOfHeroes")

target_include_directories(Game PRIVATE src)
target_link_libraries(Game PRIVATE
	Common UtilitiesLib FreeType::FreeType GLEW::GLEW JPEG::JPEG
	jpge::jpgd Vorbis::vorbisfile PhysX::Loader PhysX::Cooking
	NvDxt::NvDxt CubeMapGen::CubeMapGen Cg::Cg Cg::CgGL
	NvParse::NvParse AlienFX::AlienFX NvCpl::NvCpl
	opengl32 glu32 ddraw dinput8 dsound winmm dxguid imm32)
target_compile_definitions(Game PRIVATE
	CLIENT USEZLIB _WINDOWS _MBCS SUBSTANCE_PLATFORM_OGLCG
	_CRT_SECURE_NO_DEPRECATE)
target_compile_options(Game PRIVATE
	$<$<AND:$<CONFIG:Release,OptDebug>,$<COMPILE_LANGUAGE:C,CXX>>:/Gy;/Oi;/Zi>)
target_link_options(Game PRIVATE /LARGEADDRESSAWARE
	$<$<CONFIG:Release,OptDebug>:/DEBUG;/OPT:REF;/OPT:ICF>)
# v143 14.44 crashes optimizing showGridExternal in this file.
set_source_files_properties(src/edit/edit_drawlines.c PROPERTIES
	COMPILE_OPTIONS "$<$<CONFIG:Release,OptDebug>:/Od;/GL->")

include(StructParser)
StructParse(Game)
cox_stage_physx(Game)
cox_stage_cg(Game)
