cmake_minimum_required(VERSION 3.24)
include("${COX_STAGE_MANIFEST}")

function(copy_runtime_file source destination)
	if(NOT EXISTS "${source}")
		message(FATAL_ERROR "Missing runtime file: ${source}")
	endif()
	cmake_path(NORMAL_PATH source OUTPUT_VARIABLE source_key)
	cmake_path(NORMAL_PATH destination OUTPUT_VARIABLE destination_key)
	if(CMAKE_HOST_WIN32)
		string(TOLOWER "${source_key}" source_key)
		string(TOLOWER "${destination_key}" destination_key)
	endif()
	if(NOT source_key STREQUAL destination_key)
		file(COPY_FILE "${source}" "${destination}" ONLY_IF_DIFFERENT)
	endif()
endfunction()

function(stage_directory directory)
	file(MAKE_DIRECTORY "${directory}")
	# Also serialize independent build processes using the same output folder.
	file(LOCK "${directory}/.cox-runtime.lock" GUARD FUNCTION TIMEOUT 60)
	foreach(source IN LISTS stage_FILES)
		get_filename_component(name "${source}" NAME)
		copy_runtime_file("${source}" "${directory}/${name}")
	endforeach()
	foreach(entry IN LISTS stage_RENAMED)
		if(NOT entry MATCHES "^(.+)\\|([^/\\\\|]+)$")
			message(FATAL_ERROR "Invalid runtime alias: ${entry}")
		endif()
		copy_runtime_file("${CMAKE_MATCH_1}" "${directory}/${CMAKE_MATCH_2}")
	endforeach()
endfunction()

set(staged_directories "")
foreach(directory IN LISTS stage_DIRECTORIES)
	cmake_path(NORMAL_PATH directory)
	set(key "${directory}")
	if(CMAKE_HOST_WIN32)
		string(TOLOWER "${key}" key)
	endif()
	if(key IN_LIST staged_directories)
		continue()
	endif()
	stage_directory("${directory}")
	list(APPEND staged_directories "${key}")
endforeach()
